### PR TITLE
Approval workflow

### PR DESCRIPTION
**Pull request by re7w12u**
this PR adds an approval Workflow to the projet

### CODE REVIEW

**Review by re7w12u — COMMENTED** [review]
everything's fine

**Review by re7w12u — COMMENTED** [review]
this is ok

**Review by re7w12u — COMMENTED** [review]
ok

**Review by kairos-soft — APPROVED** [review]
it's fine

**Review by kairos-soft — APPROVED** [review]
ok

**Review by kairos-soft — APPROVED** [review]

**Pull request merged**
